import { chromium } from "playwright";
const url="https://viralcreator.vercel.app/videos";
await new Promise(r=>setTimeout(r,30000));
const browser=await chromium.launch({headless:false});
const page=await browser.newPage();
page.on("console",m=>console.log("B:",m.text()));
await page.goto(url,{waitUntil:"networkidle"});
await page.locator('input[placeholder*="tijeras"]').fill("tijeras con laser");
await page.locator('button:has-text("Buscar")').click();
console.log("Buscar click");
await page.waitForTimeout(5000);
const frame=page.frameLocator('iframe[title="TikTok"]');
try{
  await frame.locator('.card').first().waitFor({timeout:10000});
  console.log("cards found", await frame.locator('.card').count());
  await frame.locator('.card').first().click();
  await page.waitForTimeout(400);
  await frame.locator('.card').nth(1).click();
  console.log("selected 2");
  await page.waitForTimeout(3000);
} catch(e){console.log("frame error",e.message);}
const listo=page.locator('button:has-text("Listo")');
console.log("Listo visible",await listo.isVisible().catch(()=>false));
await listo.click();
console.log("Listo click");
await page.waitForTimeout(2000);
console.log("After 2s has Elige modo:", (await page.content()).includes("Elige modo"));
console.log("Has tiktokLinks:", (await page.content()).includes("tiktokLinks"));
await page.waitForTimeout(13000);
console.log("After Listo 15s, has Elige modo:", (await page.content()).includes("Elige modo"));
console.log("Has Cargando:", (await page.content()).includes("Cargando"));
console.log("Has Procesando:", (await page.content()).includes("Procesando"));
console.log("Has finalVideo:", (await page.content()).includes("Guardar"));
console.log("Has No hay clips:", (await page.content()).includes("No hay clips"));
await page.waitForTimeout(5000);
console.log("After 20s has finalVideo:", (await page.content()).includes("Guardar"));
await page.screenshot({path:"C:/Users/Paquito/AppData/Local/Temp/opencode/full.png", fullPage:true});
console.log("done");
await browser.close();
