import { chromium } from "playwright";
const url = "https://viralcreator.vercel.app/videos";
const link = "https://www.youtube.com/shorts/9FDVvWR91ww";
const browser = await chromium.launch({ headless: false });
const page = await browser.newPage();
page.on("console", m => console.log("B:", m.text()));
await page.goto(url, { waitUntil: "networkidle" });
await page.locator('input[placeholder*="youtube.com/shorts"]').fill(link);
await page.locator('button:has-text("Añadir YT")').click();
await page.waitForTimeout(500);
console.log("ytLinks added:", (await page.content()).includes("9FDVvWR91ww"));
await page.locator('button:has-text("Descargar YT sin marca")').click();
console.log("Download clicked");
await page.waitForTimeout(8000);
const content = await page.content();
console.log("Elige modo:", content.includes("Elige modo"));
console.log("Guardar:", content.includes("Guardar"));
console.log("has YT error:", content.includes("No se pudo"));
await page.waitForTimeout(12000);
console.log("After 20s Elige modo:", (await page.content()).includes("Elige modo"));
console.log("After 20s Guardar:", (await page.content()).includes("Guardar"));
await page.screenshot({ path: "C:/Users/Paquito/AppData/Local/Temp/opencode/yt.png", fullPage: true });
console.log("done");
await browser.close();